mappings:
- page_id: '335544381'
  title: 📊 Data, ETLs, Tools & Automations
  pattern: '**/📊-data,-etls,-tools-&-automations/**'
- page_id: '335773697'
  title: Data Architecture
  parent_id: '335544381'
  pattern: '**/data-architecture/**'
- page_id: '524550146'
  title: '[folder] SQL'
  parent_id: '335544381'
  pattern: '**/sql/**'
- page_id: '393117697'
  title: SQL Server Configuration & Governance Handbook
  parent_id: '524550146'
  pattern: '**/sql-server-configuration-&-governance-handbook/**'
- page_id: '525762561'
  title: '[folder] Data Warehouse'
  parent_id: '524550146'
  pattern: '**/data-warehouse/**'
- page_id: '526843905'
  title: '[folder] DE-DWH-PROCESSED'
  parent_id: '525762561'
  pattern: '**/de-dwh-processed/**'
- page_id: '526876673'
  title: '[folder] DE-DWH-RAW'
  parent_id: '525762561'
  pattern: '**/de-dwh-raw/**'
- page_id: '526909441'
  title: '[folder] DE-DWH-PROD'
  parent_id: '525762561'
  pattern: '**/de-dwh-prod/**'
- page_id: '524910598'
  title: '[folder] Transactional Database'
  parent_id: '524550146'
  pattern: '**/transactional-database/**'
- page_id: '202539010'
  title: DE-SQL
  parent_id: '524910598'
  pattern: '**/de-sql/**'
- page_id: '202506242'
  title: Designer Eyes Inc_$Purch_ Inv_ Line
  parent_id: '202539010'
  pattern: '**/designer-eyes-inc_$purch_-inv_-line/**'
- page_id: '202702850'
  title: Designer Eyes Inc_$Purch_ Rcpt_ Line
  parent_id: '202539010'
  pattern: '**/designer-eyes-inc_$purch_-rcpt_-line/**'
- page_id: '202801153'
  title: Designer Eyes Inc_$Return Shipment Line
  parent_id: '202539010'
  pattern: '**/designer-eyes-inc_$return-shipment-line/**'
- page_id: '525303810'
  title: '[folder] Products'
  parent_id: '335544381'
  pattern: '**/products/**'
- page_id: '187793411'
  title: Raw to Product Catalog ETL
  parent_id: '525303810'
  pattern: '**/raw-to-product-catalog-etl/**'
- page_id: '218005506'
  title: Data Format Reference Guide
  parent_id: '187793411'
  pattern: '**/data-format-reference-guide/**'
- page_id: '525205506'
  title: '[folder] Financial'
  parent_id: '335544381'
  pattern: '**/financial/**'
- page_id: '175276044'
  title: Price Calculator ETL
  parent_id: '525205506'
  pattern: '**/price-calculator-etl/**'
- page_id: '201687041'
  title: Min Price Tests
  parent_id: '175276044'
  pattern: '**/min-price-tests/**'
- page_id: '162004995'
  title: Direct Cost Calculator ETL
  parent_id: '525205506'
  pattern: '**/direct-cost-calculator-etl/**'
- page_id: '525533185'
  title: '[folder] Reports & Analytics'
  parent_id: '335544381'
  pattern: '**/reports-&-analytics/**'
- page_id: '525402114'
  title: '[folder] Amazon'
  parent_id: '335544381'
  pattern: '**/amazon/**'
- page_id: '172654600'
  title: Amazon Inventory ETL Script Documentation
  parent_id: '525402114'
  pattern: '**/amazon-inventory-etl-script-documentation/**'
- page_id: '525565953'
  title: '[folder] Shopify'
  parent_id: '335544381'
  pattern: '**/shopify/**'
- page_id: '525729793'
  title: '[folder] eBay'
  parent_id: '335544381'
  pattern: '**/ebay/**'
- page_id: '524877832'
  title: '[folder] 3rd Party Software Integrations'
  parent_id: '335544381'
  pattern: '**/3rd-party-software-integrations/**'
- page_id: '525664257'
  title: '[folder] Health & Monitoring'
  parent_id: '335544381'
  pattern: '**/health-&-monitoring/**'
- page_id: '524615816'
  title: '[folder] Web Scraping'
  parent_id: '335544381'
  pattern: '**/web-scraping/**'
- page_id: '207912961'
  title: Base Scraper
  parent_id: '524615816'
  pattern: '**/base-scraper/**'
- page_id: '207781893'
  title: Sunglass Hut Scraper
  parent_id: '524615816'
  pattern: '**/sunglass-hut-scraper/**'
- page_id: '208535555'
  title: Basspro Scraper
  parent_id: '524615816'
  pattern: '**/basspro-scraper/**'
- page_id: '208371713'
  title: Dillard's Scraper
  parent_id: '524615816'
  pattern: '**/dillard''s-scraper/**'
- page_id: '208044036'
  title: Dicks Sporting Goods Scraper
  parent_id: '524615816'
  pattern: '**/dicks-sporting-goods-scraper/**'
- page_id: '141918216'
  title: Luxottica wholesale portal data pull
  parent_id: '524615816'
  pattern: '**/luxottica-wholesale-portal-data-pull/**'
- page_id: '525205505'
  title: '[folder] Legacy Processes'
  parent_id: '335544381'
  pattern: '**/legacy-processes/**'
- page_id: '181764102'
  title: Data integration Repo Docs
  parent_id: '525205505'
  pattern: '**/data-integration-repo-docs/**'
- page_id: '525303809'
  title: '[folder] Deprecated Processes'
  parent_id: '335544381'
  pattern: '**/deprecated-processes/**'
- page_id: '44072988'
  title: Image ETL Process
  parent_id: '525303809'
  pattern: '**/image-etl-process/**'
- page_id: '30572560'
  title: Image FTP Process Logic
  parent_id: '44072988'
  pattern: '**/image-ftp-process-logic/**'
- page_id: '44236855'
  title: Old Image Process - Nodejs Method (Deprecated)
  parent_id: '30572560'
  pattern: '**/old-image-process---nodejs-method-(deprecated)/**'
- page_id: '48627713'
  title: Naming convention
  parent_id: '44072988'
  pattern: '**/naming-convention/**'
- page_id: '233537537'
  title: New Image Process
  parent_id: '44072988'
  pattern: '**/new-image-process/**'
warn_on_no_match: true
